### ISSUE TITLE
Accessibility sandbox hole

### ISSUE THREAD

**Issue by A6GibKm** [flathub/dev.bsnes.bsnes#6]
I was wondering what purpose does the `org.a11y.*` hole at https://github.com/flathub/dev.bsnes.bsnes/blob/master/dev.bsnes.bsnes.yaml#L15 serves. In most cases it shouldn't be necessary to expose this DBus interface.

Even if it is needed, most likely only `org.a11y.Bus` is needed.

**Comment by ghisvail** [comment]
> In most cases it shouldn't be necessary to expose this DBus interface.

I believe there was a warning about it otherwise. 

> Even if it is needed, most likely only org.a11y.Bus is needed.

Possibly. Feel free to provide a PR for it :+1:
